version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: veterinary-frontend:latest
    container_name: veterinary-frontend
    restart: unless-stopped
    ports:
      - "90:80"
    networks:
      - veterinaria-net # Aseg√∫rate que esta red exista o usa la default de Dokploy

networks:
  veterinaria-net:
    external: true